Repository sketch-hq/SketchAPI, pull requests merged in 2019-05, with the labels that each got.

#474 Add API Release Notes Section
  docs-website/_sass/base/_typography.scss
  docs-website/pages/plugins-internal-api.md
  docs-website/pages/plugins-releases-53.md
  docs-website/pages/plugins-releases-54.md
Labels: waffle:wip

#484 update console core module
  core-modules/package.json
Labels: waffle:wip

#475 Add Textarea option to UI.getInputFromUser
  .eslintrc.yml
  CHANGELOG.json
  Source/ui/UI.js
  docs/api/UI.md
Labels: waffle:wip

#487 fix getParentSymbolMaster for SymbolMaster
  CHANGELOG.json
  Source/dom/layers/SymbolMaster.js
  Source/dom/layers/__tests__/Layer.test.js
  docs/api/Layer.md
Labels: waffle:wip

#486 Fix setting layers of a group when the layers already had a parent
  CHANGELOG.json
  Source/dom/layers/Group.js
Labels: waffle:review

#357 add find method
  .eslintrc.yml
  CHANGELOG.json
  Source/dom/Factory.js
  Source/dom/__tests__/find.test.js
  Source/dom/find.js
  Source/dom/index.js
  docs/api/find.md
Labels: waffle:review

#497 Code Review: Export Pages with options break in Sketch 55 Beta (#24552)
  Source/dom/__tests__/export.test.js
  Source/dom/export.js
  Source/dom/layers/Shape.js
  Source/dom/models/__tests__/CurvePoint.test.js
  Source/dom/models/__tests__/Document.test.js
  Source/dom/models/__tests__/ImportableObject.test.js
  Source/dom/models/__tests__/Library.test.js
  package-lock.json
  package.json
Labels: waffle:wip

#476 add docs for handlers and manifest schema
  docs/pages/plugins-manifest.md
  docs/sketch-plugin-manifest-schema.json
Labels: waffle:wip

#491 add philosophy doc
  README.md
  docs-website/README.md
  docs/README.md
  docs/philosophy.md
Labels: waffle:wip

#492 expose substrings in Text.fragments
  CHANGELOG.json
  Source/dom/layers/Text.js
  Source/dom/layers/__tests__/Text.test.js
  docs/api/Text.md
Labels: waffle:wip

#493 fix logging MOStruct
  core-modules/package.json
Labels: waffle:wip

#519 Use Jekyll's native live reload feature
  docs-website/Gemfile
  docs-website/Gemfile.lock
  docs-website/_plugins/symlink_watch.rb
  docs-website/run
Labels: status: ready for merge

#520 Add docs for an empty sample file
  docs/pages/file-format-reference-empty.md
  docs/pages/file-format-reference-overview.md
  reference-files/empty/55/output.sketch
  reference-files/empty/55/output/document.json
  reference-files/empty/55/output/meta.json
  reference-files/empty/55/output/pages/3E254C78-B274-4D23-BED6-B35C4F2B47C8.json
  reference-files/empty/55/output/user.json
  reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/command.js
  reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/manifest.json
Labels: status: ready for review

#526 Improve manifest.json docs
  docs/pages/plugins-create-plugin.md
  docs/pages/plugins-manifest.md
  reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/command.js
Labels: status: ready for review
