Repository sketch-hq/SketchAPI, pull requests merged in 2019-06, with the labels that each got.

#528 Add reference file automation scripts, and shape and symbol reference plugins
  docs/pages/file-format-reference-empty.md
  docs/pages/file-format-reference-shapes.md
  docs/pages/file-format-reference-symbols.md
  package-lock.json
  package.json
  reference-files/55.1/empty/output.sketch
  reference-files/55.1/empty/output/document.json
  reference-files/55.1/empty/output/meta.json
  reference-files/55.1/empty/output/pages/B41D58CC-5BF0-40DA-8EC6-F3DC4AA316C5.json
  reference-files/55.1/empty/output/user.json
  reference-files/55.1/shapes/output.sketch
  reference-files/55.1/shapes/output/document.json
  reference-files/55.1/shapes/output/meta.json
  reference-files/55.1/shapes/output/pages/8551CF62-87B2-4B67-964D-A1FE01B3B19C.json
  reference-files/55.1/shapes/output/previews/preview.png
  reference-files/55.1/shapes/output/user.json
  reference-files/55.1/symbols/output.sketch
  reference-files/55.1/symbols/output/document.json
  reference-files/55.1/symbols/output/meta.json
  reference-files/55.1/symbols/output/pages/D47D0E38-6BB8-4941-A1C6-FD20518413AA.json
  reference-files/55.1/symbols/output/previews/preview.png
  reference-files/55.1/symbols/output/user.json
  reference-files/empty/55/output.sketch
  reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/command.js
  reference-files/empty/55/plugin.sketchplugin/Contents/Sketch/manifest.json
  reference-files/plugin.sketchplugin/Contents/Sketch/empty.js
  reference-files/plugin.sketchplugin/Contents/Sketch/manifest.json
  reference-files/plugin.sketchplugin/Contents/Sketch/shapes.js
  reference-files/plugin.sketchplugin/Contents/Sketch/symbols.js
  scripts/generate-reference-files-md.js
  scripts/generate-reference-files.js
Labels: status: ready for review

#533 Add api for exposing and changing a document's color space
  CHANGELOG.json
  Source/dom/models/Document.js
  Source/dom/models/__tests__/Document.test.js
  docs/api/Document.md
Labels: status: ready for review

#535 Adding documentation regarding double underscores to call objective c methods
  docs/pages/plugins-cocoascript.md
Labels: status: ready for qa

#539 Add ref files for images and shape paths
  docs/pages/file-format-reference-images.md
  docs/pages/file-format-reference-shape-paths.md
  reference-files/55.1/images/output.sketch
  reference-files/55.1/images/output/document.json
  reference-files/55.1/images/output/images/5e66bb5eef61a7941be4a04626356fcd1a3a1742.png
  reference-files/55.1/images/output/meta.json
  reference-files/55.1/images/output/pages/85B7DD75-A7B2-4EE3-BFAE-4E51AA0E79BF.json
  reference-files/55.1/images/output/previews/preview.png
  reference-files/55.1/images/output/user.json
  reference-files/55.1/shape-paths/output.sketch
  reference-files/55.1/shape-paths/output/document.json
  reference-files/55.1/shape-paths/output/meta.json
  reference-files/55.1/shape-paths/output/pages/5F2CAFEF-72E4-49B3-A102-7C7AE30B59EC.json
  reference-files/55.1/shape-paths/output/previews/preview.png
  reference-files/55.1/shape-paths/output/user.json
  reference-files/plugin.sketchplugin/Contents/Sketch/images.js
  reference-files/plugin.sketchplugin/Contents/Sketch/manifest.json
  reference-files/plugin.sketchplugin/Contents/Sketch/shape-paths.js
Labels: status: ready for review

#517 Added page on normalized coordinates
  docs-website/images/developer/file-format-coordinates-frame-parent.png
  docs-website/images/developer/file-format-coordinates-frame.png
  docs-website/images/developer/file-format-coordinates-points.png
  docs/pages/file-format-coordinates.md
Labels: status: in review

#543 Order ref file doc pages in sidebar
  docs/pages/file-format-reference-empty.md
  docs/pages/file-format-reference-groups.md
  docs/pages/file-format-reference-images.md
  docs/pages/file-format-reference-library-styles.md
  docs/pages/file-format-reference-library-symbols.md
  docs/pages/file-format-reference-shape-paths.md
  docs/pages/file-format-reference-shapes.md
  docs/pages/file-format-reference-symbol-overrides.md
  docs/pages/file-format-reference-symbols.md
  docs/pages/file-format-reference-text.md
  reference-files/plugin.sketchplugin/Contents/Sketch/manifest.json
  scripts/generate-reference-files-md.js
Labels: status: ready for review
